# Generated by Django 4.2.16 on 2025-05-10 21:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0005_remove_assessmentscore_userid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandwrittenQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('answer_key', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='handwritten_questions_images/')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handwritten_questions', to='assessment.assessment')),
            ],
        ),
    ]
