# Generated by Django 4.2.16 on 2025-05-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenquestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwrittenquestion',
            name='answer_key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='handwrittenquestion',
            name='question',
            field=models.CharField(max_length=50),
        ),
    ]
