# Generated by Django 4.2.16 on 2025-05-31 18:08

import HandwrittenQuestion.models
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandwrittenQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('answer_key', models.TextField(blank=True, null=True)),
                ('question_grade', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handwritten_questions', to='assessment.assessment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handwritten_questions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandwrittenQuestionScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handwritten_scores', to='enrollments.enrollments')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='HandwrittenQuestion.handwrittenquestion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['question', 'enrollment'], name='Handwritten_questio_66c38e_idx'), models.Index(fields=['created_at'], name='Handwritten_created_5276a9_idx')],
                'unique_together': {('question', 'enrollment')},
            },
        ),
        migrations.AddIndex(
            model_name='handwrittenquestion',
            index=models.Index(fields=['assessment'], name='Handwritten_assessm_ed2795_idx'),
        ),
        migrations.AddIndex(
            model_name='handwrittenquestion',
            index=models.Index(fields=['created_by'], name='Handwritten_created_c500ef_idx'),
        ),
    ]
