# Generated by Django 4.2.16 on 2025-05-17 00:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HandwrittenQuestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handwrittenquestion',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='handwrittenquestionscore',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RemoveIndex(
            model_name='handwrittenquestionscore',
            name='Handwritten_created_5276a9_idx',
        ),
        migrations.RenameField(
            model_name='handwrittenquestionscore',
            old_name='updated_at',
            new_name='evaluated_at',
        ),
        migrations.RenameField(
            model_name='handwrittenquestionscore',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='handwrittenquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='handwrittenquestion',
            name='question_grade',
        ),
        migrations.RemoveField(
            model_name='handwrittenquestionscore',
            name='student_answer',
        ),
        migrations.AddField(
            model_name='handwrittenquestion',
            name='max_grade',
            field=models.PositiveSmallIntegerField(default=1, help_text='Maximum grade for this question', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handwrittenquestion',
            name='question_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handwrittenquestionscore',
            name='answer_image',
            field=models.ImageField(default=1, upload_to='handwritten_answers/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handwrittenquestionscore',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handwrittenquestion',
            name='answer_key',
            field=models.TextField(default=1, help_text='The correct answer or key points for evaluation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handwrittenquestion',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_handwritten_questions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handwrittenquestionscore',
            name='score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='handwrittenquestionscore',
            index=models.Index(fields=['submitted_at'], name='Handwritten_submitt_aca187_idx'),
        ),
    ]
