# Generated by Django 4.2.16 on 2025-06-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0002_initial'),
        ('enrollments', '0001_initial'),
        ('HandwrittenQuestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwrittenquestionscore',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handwritten_scores', to='enrollments.enrollments'),
        ),
        migrations.AddField(
            model_name='handwrittenquestionscore',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='HandwrittenQuestion.handwrittenquestion'),
        ),
        migrations.AddField(
            model_name='handwrittenquestion',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handwritten_questions', to='assessment.assessment'),
        ),
    ]
