# Generated by Django 4.2.16 on 2025-06-05 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HandwrittenQuestion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwrittenquestion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_handwritten_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='handwrittenquestionscore',
            index=models.Index(fields=['question', 'enrollment'], name='Handwritten_questio_66c38e_idx'),
        ),
        migrations.AddIndex(
            model_name='handwrittenquestionscore',
            index=models.Index(fields=['submitted_at'], name='Handwritten_submitt_aca187_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='handwrittenquestionscore',
            unique_together={('question', 'enrollment')},
        ),
        migrations.AddIndex(
            model_name='handwrittenquestion',
            index=models.Index(fields=['assessment'], name='Handwritten_assessm_ed2795_idx'),
        ),
        migrations.AddIndex(
            model_name='handwrittenquestion',
            index=models.Index(fields=['created_by'], name='Handwritten_created_c500ef_idx'),
        ),
    ]
