# Generated by Django 4.2.16 on 2025-05-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandwrittenQuestion', '0002_alter_handwrittenquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwrittenquestion',
            name='answer_key',
            field=models.TextField(blank=True, help_text='The correct answer or key points for evaluation', null=True),
        ),
        migrations.AlterField(
            model_name='handwrittenquestionscore',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='handwritten_answers/'),
        ),
    ]
