# Generated by Django 5.1.3 on 2025-06-14 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HandwrittenQuestion', '0002_initial'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='handwrittenquestion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_handwritten_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='handwrittenquestionscore',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handwritten_scores', to='enrollments.enrollments'),
        ),
        migrations.AddField(
            model_name='handwrittenquestionscore',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='HandwrittenQuestion.handwrittenquestion'),
        ),
        migrations.AddIndex(
            model_name='handwrittenquestion',
            index=models.Index(fields=['assessment'], name='Handwritten_assessm_ed2795_idx'),
        ),
        migrations.AddIndex(
            model_name='handwrittenquestion',
            index=models.Index(fields=['created_by'], name='Handwritten_created_c500ef_idx'),
        ),
        migrations.AddIndex(
            model_name='handwrittenquestionscore',
            index=models.Index(fields=['question', 'enrollment'], name='Handwritten_questio_66c38e_idx'),
        ),
        migrations.AddIndex(
            model_name='handwrittenquestionscore',
            index=models.Index(fields=['submitted_at'], name='Handwritten_submitt_aca187_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='handwrittenquestionscore',
            unique_together={('question', 'enrollment')},
        ),
    ]
