# Generated by Django 4.2.16 on 2025-05-24 18:50

import HandwrittenQuestion.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandwrittenQuestion', '0003_alter_handwrittenquestion_answer_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwrittenquestionscore',
            name='answer_image',
            field=models.ImageField(blank=True, help_text='Upload a JPEG, PNG, GIF, or BMP image file (max 5MB)', null=True, upload_to=HandwrittenQuestion.models.get_handwritten_answer_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='handwrittenquestionscore',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Text extracted from the handwritten answer image', null=True),
        ),
        migrations.AlterField(
            model_name='handwrittenquestionscore',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
