# Generated by Django 5.1.3 on 2025-06-09 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandwrittenQuestion', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwrittenquestionscore',
            name='answer_image',
            field=models.ImageField(blank=True, help_text='Upload a JPEG, PNG, GIF, or BMP image file (max 5MB)', null=True, upload_to='handwritten_answers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp'])]),
        ),
    ]
