# Generated by Django 4.2.16 on 2025-05-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandwrittenQuestion', '0004_alter_handwrittenquestionscore_answer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwrittenquestion',
            name='section_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Section number within the assessment'),
            preserve_default=False,
        ),
    ]
