# Generated by Django 4.2.16 on 2025-06-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollments',
            name='total_grade',
            field=models.FloatField(default=0),
        ),
    ]
