# Generated by Django 5.1.4 on 2025-05-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollments',
            name='is_completed',
            field=models.BooleanField(default=True),
        ),
    ]
