# Generated by Django 4.2.16 on 2025-05-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollments',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
