# Generated by Django 5.1.3 on 2025-06-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_enrollments_total_grade'),
        ('enrollments', '0002_initial'),
    ]

    operations = [
    ]
