# Generated by Django 5.2.2 on 2025-06-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_enrollments_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollments',
            name='retries',
            field=models.IntegerField(default=0),
        ),
    ]
