# Generated by Django 5.2.2 on 2025-06-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_enrollments_retries'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollments',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollments',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollments',
            name='is_summer_enrollment',
            field=models.BooleanField(default=False),
        ),
    ]
