# Generated by Django 5.2.2 on 2025-06-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_alter_enrollments_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollments',
            name='retries',
        ),
    ]
