# Generated by Django 5.1.3 on 2025-06-14 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_merge_0002_enrollments_total_grade_0002_initial'),
        ('enrollments', '0006_remove_enrollments_retries'),
    ]

    operations = [
    ]
