# Generated by Django 5.1.3 on 2025-06-14 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_merge_20250614_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollments',
            name='total_grade',
        ),
    ]
