# Generated by Django 4.2.16 on 2025-05-16 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapter', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureprogress',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecture',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='chapter.chapter'),
        ),
        migrations.AlterUniqueTogether(
            name='lectureprogress',
            unique_together={('user', 'lecture')},
        ),
    ]
