# Generated by Django 4.2.16 on 2025-04-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='lectures/attachments/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lectures/videos/'),
        ),
    ]
