# Generated by Django 4.2.16 on 2025-06-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_enrollments_total_grade'),
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lectureprogress',
            unique_together=set(),
        ),
        migrations.AddField(

            model_name='lectureprogress',
            name='enrollment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enrollments.enrollments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectureprogress',
            name='time_spent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lectureprogress',
            unique_together={('enrollment', 'lecture')},
        ),
        migrations.RemoveField(
            model_name='lectureprogress',
            name='user',
        ),
    ]

