# Generated by Django 4.2.16 on 2025-04-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_alter_lecture_attachment_alter_lecture_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='duration',
        ),
    ]
