# Generated by Django 5.1.3 on 2025-06-14 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_initial'),
        ('lecture', '0002_lecture_updated_at'),
    ]

    operations = [
    ]
