# Generated by Django 5.1.3 on 2025-06-14 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0008_remove_enrollments_total_grade'),
        ('lecture', '0003_merge_0002_initial_0002_lecture_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lectureprogress',
            unique_together={('enrollment', 'lecture')},
        ),
        migrations.RemoveField(
            model_name='lectureprogress',
            name='user',
        ),
    ]
