# Generated by Django 5.1.4 on 2025-04-30 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0001_initial'),
        ('lecture', '0006_alter_lectureprogress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='chapter.chapter'),
        ),
    ]
