# Generated by Django 5.1.3 on 2024-11-25 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instituition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.institution'),
        ),
    ]
