# Generated by Django 4.2.16 on 2025-06-05 16:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mcq_answers', models.JSONField(default=dict, help_text='Dictionary of question_id: selected_answer')),
                ('handwritten_answers', models.JSONField(default=dict, help_text='Dictionary of question_id: image_path')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_submitted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
