# Generated by Django 5.1.3 on 2025-06-14 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='assessments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='scores', to='assessment.assessment'),
        ),
    ]
