# Generated by Django 4.2.16 on 2025-05-09 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0002_assessmentscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='institution',
            field=models.ForeignKey(limit_choices_to={'role': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
