# Generated by Django 4.2.16 on 2025-05-16 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
        ('assessment', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentscore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='enrollment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='enrollments.enrollments'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='assessmentscore',
            unique_together={('enrollment', 'assessment')},
        ),
        migrations.RemoveField(
            model_name='assessmentscore',
            name='student',
        ),
    ]
