# Generated by Django 4.2.16 on 2025-06-08 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='accepting_submissions',
        ),
    ]
