# Generated by Django 5.1.3 on 2025-06-09 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='accepting_submissions',
        ),
    ]
