# Generated by Django 4.2.16 on 2025-05-09 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentscore',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_assessmet', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
