# Generated by Django 4.2.16 on 2025-05-24 18:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
        ('assessment', '0003_alter_assessmentscore_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mcq_answers', models.JSONField(default=dict, help_text='Dictionary of question_id: selected_answer')),
                ('handwritten_answers', models.JSONField(default=dict, help_text='Dictionary of question_id: image_path')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessment.assessment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_submissions', to='enrollments.enrollments')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('assessment', 'enrollment')},
            },
        ),
    ]
