# Generated by Django 5.1.3 on 2025-06-14 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_initial'),
        ('assessment', '0003_remove_assessment_accepting_submissions'),
    ]

    operations = [
    ]
