# Generated by Django 4.2.16 on 2025-05-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_assessmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='context_file',
            field=models.FileField(blank=True, help_text='PDF or text file containing the context for dynamic MCQ generation', null=True, upload_to='assessment_contexts/'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='context_text',
            field=models.TextField(blank=True, help_text='Text context for dynamic MCQ generation', null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='number_of_questions',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of questions to generate for dynamic MCQ', null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('Exam', 'Exam'), ('Assignment', 'Assignment'), ('Quiz', 'Quiz'), ('Dynamic_MCQ', 'Dynamic MCQ')], max_length=50),
        ),
    ]
