# Generated by Django 4.2.16 on 2025-05-09 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0004_assessmentscore_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentscore',
            name='userId',
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='student',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessmentscore',
            name='submit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
