# Generated by Django 4.2.16 on 2025-05-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_assessment_context_file_assessment_context_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('1', 'Very Easy'), ('2', 'Easy'), ('3', 'Medium'), ('4', 'Hard'), ('5', 'Very Hard')], default='3', max_length=20, null=True),
        ),
    ]
