# Generated by Django 4.2.16 on 2025-05-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
        ('assessment', '0006_alter_assessment_difficulty_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentscore',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='assessmentscore',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='assessmentscore',
            unique_together={('assessment', 'enrollment')},
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='context_file',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='context_text',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='number_of_questions',
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('Exam', 'Exam'), ('Assignment', 'Assignment'), ('Quiz', 'Quiz')], max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmentscore',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='AssessmentSubmission',
        ),
    ]
