# Generated by Django 5.1.4 on 2025-04-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0001_initial'),
        ('courses', '0010_course_semester'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('title', 'course')},
        ),
    ]
