# Generated by Django 5.1.3 on 2025-06-14 03:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DynamicMCQ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQQuestionScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('selected_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.DecimalField(
                    decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dynamic_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='scores', to='DynamicMCQ.dynamicmcqquestions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
