# Generated by Django 4.2.16 on 2025-06-10 18:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        ('DynamicMCQ', '0001_initial'),
        ('mcqQuestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQQuestionScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dynamic_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='DynamicMCQ.dynamicmcqquestions')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_scores', to='enrollments.enrollments')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='mcqQuestion.mcqquestion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['question', 'enrollment'], name='MCQQuestion_questio_1dfddc_idx'), models.Index(fields=['dynamic_question', 'enrollment'], name='MCQQuestion_dynamic_cd2160_idx'), models.Index(fields=['created_at'], name='MCQQuestion_created_ac3c96_idx')],
                'unique_together': {('question', 'enrollment'), ('dynamic_question', 'enrollment')},
            },
        ),
    ]
