# Generated by Django 4.2.16 on 2025-06-10 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        ('MCQQuestionScore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestionscore',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_scores', to='enrollments.enrollments'),
        ),
    ]
