# Generated by Django 4.2.16 on 2025-05-16 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MCQQuestionScore', '0002_initial'),
        ('mcqQuestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestionscore',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_scores', to='mcqQuestion.mcqquestion'),
        ),
    ]
