# Generated by Django 4.2.16 on 2025-05-28 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mcqQuestion', '0001_initial'),
        ('MCQQuestionScore', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestionscore',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='mcqQuestion.mcqquestion'),
        ),
        migrations.AddIndex(
            model_name='mcqquestionscore',
            index=models.Index(fields=['question', 'enrollment'], name='MCQQuestion_questio_1dfddc_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqquestionscore',
            index=models.Index(fields=['created_at'], name='MCQQuestion_created_ac3c96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mcqquestionscore',
            unique_together={('question', 'enrollment')},
        ),
    ]
