# Generated by Django 4.2.16 on 2025-05-16 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MCQQuestionScore', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestionscore',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mcqquestionscore',
            index=models.Index(fields=['question', 'student'], name='MCQQuestion_questio_150ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqquestionscore',
            index=models.Index(fields=['course'], name='MCQQuestion_course__9ead44_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqquestionscore',
            index=models.Index(fields=['created_at'], name='MCQQuestion_created_ac3c96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mcqquestionscore',
            unique_together={('question', 'student')},
        ),
    ]
