# Generated by Django 4.2.16 on 2025-05-17 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
        ('mcqQuestion', '0002_initial'),
        ('MCQQuestionScore', '0004_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mcqquestionscore',
            name='MCQQuestion_questio_150ab4_idx',
        ),
        migrations.RemoveIndex(
            model_name='mcqquestionscore',
            name='MCQQuestion_course__9ead44_idx',
        ),
        migrations.AlterUniqueTogether(
            name='mcqquestionscore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mcqquestionscore',
            name='enrollment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_scores', to='enrollments.enrollments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mcqquestionscore',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='mcqQuestion.mcqquestion'),
        ),
        migrations.AlterField(
            model_name='mcqquestionscore',
            name='selected_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='mcqquestionscore',
            unique_together={('question', 'enrollment')},
        ),
        migrations.AddIndex(
            model_name='mcqquestionscore',
            index=models.Index(fields=['question', 'enrollment'], name='MCQQuestion_questio_1dfddc_idx'),
        ),
        migrations.RemoveField(
            model_name='mcqquestionscore',
            name='course',
        ),
        migrations.RemoveField(
            model_name='mcqquestionscore',
            name='student',
        ),
    ]
