# Generated by Django 4.2.16 on 2025-05-31 19:14

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.contenttypes.models import ContentType
from mcqQuestion.models import McqQuestion
from DynamicMCQ.models import DynamicMCQQuestions

def cleanup_duplicates(apps, schema_editor):
    MCQQuestionScore = apps.get_model('MCQQuestionScore', 'MCQQuestionScore')
    db_alias = schema_editor.connection.alias

    # Get content types
    mcq_content_type = ContentType.objects.get_for_model(McqQuestion)
    dynamic_mcq_content_type = ContentType.objects.get_for_model(DynamicMCQQuestions)

    # Group by content_type, object_id, and enrollment
    seen = set()
    duplicates = []

    for score in MCQQuestionScore.objects.using(db_alias).all():
        key = (score.content_type_id, score.object_id, score.enrollment_id)
        if key in seen:
            duplicates.append(score.id)
        else:
            seen.add(key)

    # Delete duplicates
    if duplicates:
        MCQQuestionScore.objects.using(db_alias).filter(id__in=duplicates).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('MCQQuestionScore', '0005_remove_mcqquestionscore_mcqquestion_questio_150ab4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestionscore',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcqquestionscore',
            name='object_id',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
        migrations.RunPython(cleanup_duplicates),
        migrations.AlterUniqueTogether(
            name='mcqquestionscore',
            unique_together={('content_type', 'object_id', 'enrollment')},
        ),
        migrations.AddIndex(
            model_name='mcqquestionscore',
            index=models.Index(fields=['content_type', 'object_id'], name='MCQQuestion_content_b475d4_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqquestionscore',
            index=models.Index(fields=['enrollment'], name='MCQQuestion_enrollm_0d205d_idx'),
        ),
        migrations.RemoveField(
            model_name='mcqquestionscore',
            name='question',
        ),
    ]
