# Generated by Django 4.2.16 on 2025-05-31 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('MCQQuestionScore', '0005_remove_mcqquestionscore_mcqquestion_questio_150ab4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mcqquestionscore',
            name='MCQQuestion_questio_1dfddc_idx',
        ),
        migrations.AlterUniqueTogether(
            name='mcqquestionscore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mcqquestionscore',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcqquestionscore',
            name='object_id',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcqquestionscore',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('dynamic_mcq', 'Dynamic MCQ')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='mcqquestionscore',
            unique_together={('content_type', 'object_id', 'enrollment')},
        ),
        migrations.AddIndex(
            model_name='mcqquestionscore',
            index=models.Index(fields=['content_type', 'object_id'], name='MCQQuestion_content_b475d4_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqquestionscore',
            index=models.Index(fields=['enrollment'], name='MCQQuestion_enrollm_0d205d_idx'),
        ),
        migrations.RemoveField(
            model_name='mcqquestionscore',
            name='question',
        ),
    ]
