# Generated by Django 4.2.16 on 2025-05-31 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcqQuestion', '0005_mcqquestion_section_number'),
        ('enrollments', '0002_initial'),
        ('MCQQuestionScore', '0006_cleanup_duplicates'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mcqquestionscore',
            name='MCQQuestion_content_b475d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='mcqquestionscore',
            name='MCQQuestion_enrollm_0d205d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='mcqquestionscore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mcqquestionscore',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='mcqQuestion.mcqquestion'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='mcqquestionscore',
            unique_together={('question', 'enrollment')},
        ),
        migrations.RemoveField(
            model_name='mcqquestionscore',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='mcqquestionscore',
            name='object_id',
        ),
    ]
