# Generated by Django 4.2.16 on 2025-05-31 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicMCQ', '0005_remove_dynamicmcqquestions_scores'),
        ('mcqQuestion', '0005_mcqquestion_section_number'),
        ('enrollments', '0002_initial'),
        ('MCQQuestionScore', '0007_remove_mcqquestionscore_mcqquestion_content_b475d4_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mcqquestionscore',
            unique_together={('question', 'enrollment')},
        ),
        migrations.AddField(
            model_name='mcqquestionscore',
            name='dynamic_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='DynamicMCQ.dynamicmcqquestions'),
        ),
        migrations.AlterField(
            model_name='mcqquestionscore',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='mcqQuestion.mcqquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='mcqquestionscore',
            unique_together={('question', 'enrollment'), ('dynamic_question', 'enrollment')},
        ),
        migrations.AddIndex(
            model_name='mcqquestionscore',
            index=models.Index(fields=['dynamic_question', 'enrollment'], name='MCQQuestion_dynamic_cd2160_idx'),
        ),
    ]
