# Generated by Django 4.2.16 on 2025-06-10 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='McqQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('options', models.JSONField(help_text='List of possible answers')),
                ('answer_key', models.CharField(max_length=255)),
                ('question_grade', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('section_number', models.PositiveSmallIntegerField(help_text='Section number within the assessment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='assessment.assessment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcq_questions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assessment'], name='mcqQuestion_assessm_68dd1d_idx'), models.Index(fields=['created_by'], name='mcqQuestion_created_221ed9_idx')],
            },
        ),
    ]
