# Generated by Django 4.2.16 on 2025-05-10 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0003_alter_assessment_institution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='McqQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.JSONField()),
                ('answer_key', models.CharField(max_length=255)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='assessment.assessment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcq_questions_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
