# Generated by Django 4.2.16 on 2025-05-09 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcqQuestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcq_questions_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
