# Generated by Django 4.2.16 on 2025-05-24 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqQuestion', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcqquestion',
            old_name='answer',
            new_name='options',
        ),
    ]
