# Generated by Django 4.2.16 on 2025-05-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqQuestion', '0003_rename_answer_mcqquestion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquestion',
            name='options',
            field=models.JSONField(help_text='List of possible answers'),
        ),
    ]
