# Generated by Django 4.2.16 on 2025-05-16 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('credit_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_grade', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
