# Generated by Django 5.1.3 on 2025-06-14 03:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('passing_grade', models.FloatField(
                    blank=True, default=50.0, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('total_grade', models.PositiveSmallIntegerField(
                    blank=True, null=True)),
                ('is_summer_open', models.BooleanField(default=False)),
                ('credit_hours', models.PositiveSmallIntegerField(
                    blank=True, null=True)),
            ],
        ),
    ]
