# Generated by Django 4.2.16 on 2025-05-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
