# Generated by Django 5.2.2 on 2025-06-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_summer_open',
            field=models.BooleanField(default=False),
        ),
    ]
