# Generated by Django 5.1.4 on 2025-04-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_credit_hours_course_gpa_weight_course_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
    ]
