# Generated by Django 5.2.2 on 2025-06-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_summer_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_summer_open',
            field=models.BooleanField(default=True),
        ),
    ]
