# Generated by Django 5.1.4 on 2025-04-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='gpa_weight',
        ),
    ]
