# Generated by Django 5.1.4 on 2025-05-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
