# Generated by Django 4.2.16 on 2025-05-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_total_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='passing_grade',
            field=models.FloatField(blank=True, default=50.0, null=True),
        ),
    ]
