# Generated by Django 5.1.4 on 2025-04-12 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisite_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_courses', to='courses.course'),
        ),
    ]
