# Generated by Django 5.1.4 on 2025-04-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
