# Generated by Django 4.2.16 on 2025-06-05 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0002_initial'),
        ('CodingQuestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestionscore',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='assessment_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment'),
        ),
    ]
