# Generated by Django 5.1.3 on 2025-05-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paymob_url',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
