# Generated by Django 5.1.3 on 2024-11-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_alter_institution_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(null=True, upload_to='uploads/institution/logo'),
        ),
    ]
