# Generated by Django 5.1.3 on 2025-05-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_remove_payment_paymob_url_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.JSONField(),
        ),
    ]
