# Generated by Django 5.1.3 on 2025-05-13 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_alter_plan_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='credit_value',
        ),
    ]
