# Generated by Django 5.1.3 on 2025-05-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_remove_plan_credit_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond')], max_length=10, unique=True),
        ),
    ]
