# Generated by Django 5.1.3 on 2024-11-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_alter_institution_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/institution/logo'),
        ),
    ]
