# Generated by Django 5.1.3 on 2025-05-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_alter_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='order',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
