# Generated by Django 5.1.3 on 2025-05-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_plan_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='minimum_credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
