# Generated by Django 5.1.4 on 2025-06-04 12:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_passing_grade', models.FloatField(blank=True, default=50.0, null=True)),
                ('max_allowed_failures', models.IntegerField(blank=True, default=2, null=True)),
                ('min_gpa_required', models.FloatField(blank=True, null=True)),
                ('min_attendance_percent', models.FloatField(blank=True, default=75.0, null=True)),
            ],
        ),
    ]
