# Generated by Django 4.2.16 on 2025-05-16 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_passing_grade', models.FloatField(default=50.0)),
                ('max_allowed_failures', models.IntegerField(default=2)),
                ('use_gpa', models.BooleanField(default=False)),
                ('min_gpa_required', models.FloatField(blank=True, null=True)),
                ('require_attendance', models.BooleanField(default=False)),
                ('min_attendance_percent', models.FloatField(default=75.0)),
                ('institution', models.ForeignKey(limit_choices_to={'role': 'Institution'}, on_delete=django.db.models.deletion.CASCADE, related_name='policy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
