# Generated by Django 5.1.4 on 2025-06-04 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution_policy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionpolicy',
            name='institution',
            field=models.OneToOneField(limit_choices_to={'role': 'Institution'}, on_delete=django.db.models.deletion.CASCADE, related_name='policy', to=settings.AUTH_USER_MODEL),
        ),
    ]
