# Generated by Django 4.2.16 on 2025-05-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution_policy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionpolicy',
            name='use_gpa',
        ),
    ]
