# Generated by Django 5.2.2 on 2025-06-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_policy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionpolicy',
            name='allowed_number_of_courses_per_semester',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
    ]
