# Generated by Django 4.2.16 on 2025-05-16 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution_policy', '0002_remove_institutionpolicy_use_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionpolicy',
            name='institution',
            field=models.OneToOneField(limit_choices_to={'role': 'Institution'}, on_delete=django.db.models.deletion.CASCADE, related_name='policy', to=settings.AUTH_USER_MODEL),
        ),
    ]
