# Generated by Django 4.2.16 on 2025-05-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_policy', '0003_alter_institutionpolicy_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionpolicy',
            name='require_attendance',
        ),
        migrations.AlterField(
            model_name='institutionpolicy',
            name='max_allowed_failures',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='institutionpolicy',
            name='min_attendance_percent',
            field=models.FloatField(blank=True, default=75.0, null=True),
        ),
        migrations.AlterField(
            model_name='institutionpolicy',
            name='min_passing_grade',
            field=models.FloatField(blank=True, default=50.0, null=True),
        ),
    ]
