# Generated by Django 5.2.2 on 2025-06-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution_policy', '0003_institutionpolicy_allowed_number_of_courses_per_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutionpolicy',
            old_name='allowed_number_of_courses_per_semester',
            new_name='max_allowed_courses_per_semester',
        ),
    ]
