# Generated by Django 5.2.2 on 2025-06-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution_policy', '0004_rename_allowed_number_of_courses_per_semester_institutionpolicy_max_allowed_courses_per_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutionpolicy',
            old_name='min_passing_grade',
            new_name='min_passing_percentage',
        ),
    ]
