# Generated by Django 5.2.2 on 2025-06-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_policy', '0005_rename_min_passing_grade_institutionpolicy_min_passing_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionpolicy',
            name='summer_registration_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionpolicy',
            name='year_registration_open',
            field=models.BooleanField(default=False),
        ),
    ]
