# Generated by Django 5.2.2 on 2025-06-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_policy', '0006_institutionpolicy_summer_registration_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionpolicy',
            name='promotion_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
