# Generated by Django 4.2.16 on 2025-06-10 18:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('function_signature', models.CharField(max_length=255)),
                ('language_id', models.IntegerField(choices=[(71, 'Python'), (62, 'Java'), (50, 'C'), (54, 'C++'), (51, 'C#'), (63, 'JavaScript'), (74, 'TypeScript'), (68, 'PHP')], default=71)),
                ('difficulty', models.CharField(choices=[('1', 'Very Easy'), ('2', 'Easy'), ('3', 'Medium'), ('4', 'Hard'), ('5', 'Very Hard')], default='3', max_length=1)),
                ('max_grade', models.IntegerField(default=5)),
                ('section_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CodingQuestionScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('student_answer', models.TextField()),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='Code_Questions.codingquestion')),
            ],
        ),
        migrations.CreateModel(
            name='CodingScoreTestInteractions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('passed', models.BooleanField(default=False)),
                ('questionScore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Code_Questions.codingquestionscore')),
                ('testCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Code_Questions.testcase')),
            ],
        ),
    ]
