# Generated by Django 4.2.16 on 2025-06-08 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
        ('Code_Questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingquestionscore',
            name='student_id',
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Very Easy'), ('2', 'Easy'), ('3', 'Medium'), ('4', 'Hard'), ('5', 'Very Hard')], default='3', max_length=1),
        ),
        migrations.AddField(
            model_name='codingquestionscore',
            name='enrollment_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enrollments.enrollments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codingquestionscore',
            name='questionScore',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='language_id',
            field=models.IntegerField(choices=[(71, 'Python'), (62, 'Java'), (50, 'C'), (54, 'C++'), (51, 'C#'), (63, 'JavaScript'), (74, 'TypeScript'), (68, 'PHP')], default=71),
        ),
    ]
