# Generated by Django 4.2.16 on 2025-05-10 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('Code_Questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='assessment_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment'),
        ),
    ]
