# Generated by Django 4.2.16 on 2025-06-10 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Code_Questions', '0001_initial'),
        ('enrollments', '0001_initial'),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestionscore',
            name='enrollment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollments.enrollments'),
        ),
        migrations.AddField(
            model_name='codingquestionscore',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Code_Questions.codingquestion'),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='assessment_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment'),
        ),
    ]
