# Generated by Django 4.2.16 on 2025-06-10 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
        ('Code_Questions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='assessment_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_questions', to='assessment.assessment'),
        ),
    ]
