# Generated by Django 4.2.16 on 2025-06-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code_Questions', '0003_alter_codingquestion_assessment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='language_id',
            field=models.CharField(choices=[('python3', 'Python 3'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('php', 'PHP')], default='python3', max_length=20),
        ),
    ]
