# Generated by Django 5.1.4 on 2025-06-04 12:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicMCQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_number', models.PositiveSmallIntegerField(help_text='Section number within the assessment')),
                ('context', models.TextField(blank=True, null=True)),
                ('lecture_ids', models.JSONField(default=list, help_text='Array of lecture UUIDs')),
                ('difficulty', models.CharField(choices=[('1', 'Very Easy'), ('2', 'Easy'), ('3', 'Medium'), ('4', 'Hard'), ('5', 'Very Hard')], default='3', max_length=1)),
                ('total_grade', models.PositiveSmallIntegerField()),
                ('number_of_questions', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Dynamic MCQ',
                'verbose_name_plural': 'Dynamic MCQs',
                'ordering': ['assessment__due_date', 'section_number'],
            },
        ),
        migrations.CreateModel(
            name='DynamicMCQQuestions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('options', models.JSONField(help_text='List of options for the question')),
                ('answer_key', models.CharField(help_text='The correct answer from the options', max_length=255)),
                ('question_grade', models.PositiveSmallIntegerField()),
                ('difficulty', models.CharField(choices=[('1', 'Very Easy'), ('2', 'Easy'), ('3', 'Medium'), ('4', 'Hard'), ('5', 'Very Hard')], default='3', max_length=1)),
            ],
            options={
                'verbose_name': 'Dynamic MCQ Question',
                'verbose_name_plural': 'Dynamic MCQ Questions',
                'ordering': ['dynamic_mcq', 'id'],
            },
        ),
    ]
