# Generated by Django 4.2.16 on 2025-05-31 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicMCQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_number', models.PositiveSmallIntegerField(help_text='Section number within the assessment')),
                ('context', models.TextField(blank=True, null=True)),
                ('lecture_ids', models.JSONField(default=list, help_text='Array of lecture UUIDs')),
                ('difficulty', models.CharField(choices=[('1', 'Very Easy'), ('2', 'Easy'), ('3', 'Medium'), ('4', 'Hard'), ('5', 'Very Hard')], default='3', max_length=1)),
                ('total_grade', models.PositiveSmallIntegerField()),
                ('number_of_questions', models.PositiveSmallIntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_mcqs', to='assessment.assessment')),
            ],
            options={
                'verbose_name': 'Dynamic MCQ',
                'verbose_name_plural': 'Dynamic MCQs',
                'ordering': ['assessment__due_date', 'section_number'],
            },
        ),
        migrations.CreateModel(
            name='DynamicMCQQuestions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('options', models.JSONField(help_text='List of options for the question')),
                ('answer_key', models.CharField(help_text='The correct answer from the options', max_length=255)),
                ('question_grade', models.PositiveSmallIntegerField()),
                ('difficulty', models.CharField(choices=[('1', 'Very Easy'), ('2', 'Easy'), ('3', 'Medium'), ('4', 'Hard'), ('5', 'Very Hard')], default='3', max_length=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_mcq_questions', to=settings.AUTH_USER_MODEL)),
                ('dynamic_mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='DynamicMCQ.dynamicmcq')),
            ],
            options={
                'verbose_name': 'Dynamic MCQ Question',
                'verbose_name_plural': 'Dynamic MCQ Questions',
                'ordering': ['dynamic_mcq', 'id'],
            },
        ),
    ]
