# Generated by Django 4.2.16 on 2025-05-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicMCQ', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicmcq',
            name='attachments',
        ),
        migrations.AddField(
            model_name='dynamicmcq',
            name='lecture_ids',
            field=models.JSONField(default=list, help_text='Array of lecture UUIDs'),
        ),
    ]
