# Generated by Django 4.2.16 on 2025-06-10 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DynamicMCQ', '0001_initial'),
        ('assessment', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmcqquestions',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_mcq_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dynamicmcqquestions',
            name='dynamic_mcq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='DynamicMCQ.dynamicmcq'),
        ),
        migrations.AddField(
            model_name='dynamicmcq',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_mcqs', to='assessment.assessment'),
        ),
    ]
