# Generated by Django 5.1.4 on 2025-06-04 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DynamicMCQ', '0001_initial'),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmcq',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_mcqs', to='assessment.assessment'),
        ),
    ]
