# Generated by Django 5.1.4 on 2025-06-04 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DynamicMCQ', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmcqquestions',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_mcq_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dynamicmcqquestions',
            name='dynamic_mcq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='DynamicMCQ.dynamicmcq'),
        ),
    ]
