# Generated by Django 4.2.16 on 2025-05-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicMCQ', '0002_remove_dynamicmcq_attachments_dynamicmcq_lecture_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmcqquestions',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Very Easy'), ('2', 'Easy'), ('3', 'Medium'), ('4', 'Hard'), ('5', 'Very Hard')], default='3', max_length=1),
        ),
    ]
