# Generated by Django 4.2.16 on 2025-06-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicMCQ', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmcq',
            name='num_options',
            field=models.PositiveSmallIntegerField(default=4, help_text='Number of options per question (2-6)'),
        ),
    ]
