# Generated by Django 4.2.16 on 2025-05-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQQuestionScore', '0005_remove_mcqquestionscore_mcqquestion_questio_150ab4_idx_and_more'),
        ('DynamicMCQ', '0003_dynamicmcqquestions_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmcqquestions',
            name='scores',
            field=models.ManyToManyField(blank=True, related_name='dynamic_mcq_questions', to='MCQQuestionScore.mcqquestionscore'),
        ),
    ]
