# Generated by Django 5.1.3 on 2025-06-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicMCQ', '0003_dynamicmcq_num_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmcqquestions',
            name='question_grade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
