# Generated by Django 4.2.16 on 2025-05-31 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicMCQ', '0004_dynamicmcqquestions_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicmcqquestions',
            name='scores',
        ),
    ]
