# Generated by Django 5.1.3 on 2025-06-14 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicMCQ', '0003_initial'),
        ('DynamicMCQ', '0004_alter_dynamicmcqquestions_question_grade'),
    ]

    operations = [
    ]
