# Generated by Django 5.1.3 on 2025-06-12 19:19

import users.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[users.validation.nationalId_length_validation]),
        ),
    ]
