# Generated by Django 5.1.3 on 2025-04-06 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='institution',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Institution', 'Institution'), ('Student', 'Student'), ('Teacher', 'Teacher'), ('Admin', 'Admin')], default='Student', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'Institution'}, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
