# Generated by Django 5.1.3 on 2025-05-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user/avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('school', 'School'), ('faculty', 'Faculty')], help_text='This field is required', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institution/logo/'),
        ),
    ]
