# Generated by Django 5.1.3 on 2025-03-19 04:17

import nanoid_field.fields
import users.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_institution_alter_user_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_code',
            field=nanoid_field.fields.NanoidField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz-', blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[users.validation.nationalId_length_validation]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Institution', 'Institution'), ('Student', 'Student'), ('Teacher', 'Teacher'), ('Admin', 'Admin')], default='Student', max_length=15),
        ),
    ]
