# Generated by Django 5.1.4 on 2025-04-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
