# Generated by Django 5.1.4 on 2025-04-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution_type',
            field=models.CharField(choices=[('school', 'School'), ('faculty', 'Faculty')], max_length=10, null=True),
        ),
    ]
