# Generated by Django 5.1.4 on 2025-04-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
